<a href="https://colab.research.google.com/github/lokeshneerasa/FEATURE_ENGINEERING/blob/main/FEATURE__ENGINEERING_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LabelEncoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
d={
    "Company":["Google","Twitter","Google","Linkedin"],
    "Role":["HR","Salesmanager","Datascientist","HR"]
}
df=pd.DataFrame(d)
label_encoder=LabelEncoder()
df['Company_n']=label_encoder.fit_transform(df['Company'])
df['Role_n']=label_encoder.fit_transform(df['Role'])
print()
print(df)


    Company           Role  Company_n  Role_n
0    Google             HR          0       1
1   Twitter   Salesmanager          2       2
2    Google  Datascientist          0       0
3  Linkedin             HR          1       1


# **MinMaxScaler**

In [ ]:
#Ex:1
import pandas as pd
d={
    "x":[10,20,30,40,50],
    "y":[25,50,75,100,125]
}
df=pd.DataFrame(d)
print(df)

    x    y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125


In [ ]:
#Ex:2 MinMaxScaler:single column
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
d={
    "x":[10,20,30,40,50],
    "y":[25,50,75,100,125]
}
df=pd.DataFrame(d)
mm_scale=MinMaxScaler(feature_range=(0,1))
print(df)
one_col=mm_scale.fit_transform(df[["x"]])
print(one_col)

    x    y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [ ]:
#Ex:3 MinMaxScaler:two columns
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
d={
    "x":[10,20,30,40,50],
    "y":[25,50,75,100,125]
}
df=pd.DataFrame(d)
mm_scale=MinMaxScaler(feature_range=(0,1))
print(df)
df[["x","y"]]=mm_scale.fit_transform(df[["x","y"]])
print(df)


    x    y
0  10   25
1  20   50
2  30   75
3  40  100
4  50  125
      x     y
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00


# **FunctionTransformer**

In [ ]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
a=[[10,20],[30,40],[50,60]]
f=np.array(a)
def add_ten(x):
  return x+10
obj=FunctionTransformer(add_ten)
result=obj.transform(f)
print(f)
print()
print(result)




[[10 20]
 [30 40]
 [50 60]]

[[20 30]
 [40 50]
 [60 70]]


# **Handling outlier**

In [ ]:
#Ex:1 A dataframe with outliers
import numpy as np
import pandas as pd
houses=pd.DataFrame()
houses['Price']=[534433, 392333, 293222, 4322032]
houses['Rooms']=[2,3,2,116]
houses['Square_Feet']=[1500, 2500, 1500, 48000]
print(houses)

     Price  Rooms  Square_Feet
0   534433      2         1500
1   392333      3         2500
2   293222      2         1500
3  4322032    116        48000


In [ ]:
#Ex:2 Filtering outlier
import numpy as np
import pandas as pd
houses=pd.DataFrame()
houses['Price']=[534433, 392333, 293222, 4322032]
houses['Rooms']=[2,3,2,116]
houses['Square_Feet']=[1500, 2500, 1500, 48000]
con1=houses['Rooms']<20
new=houses[con1]
print(new)


    Price  Rooms  Square_Feet
0  534433      2         1500
1  392333      3         2500
2  293222      2         1500


In [ ]:
#Ex:3 Mark them as outliers
import numpy as np
import pandas as pd
houses=pd.DataFrame()
houses['Price']=[534433, 392333, 293222, 4322032]
houses['Rooms']=[2,3,2,116]
houses['Square_Feet']=[1500, 2500, 1500, 48000]
houses["Outlier"]=np.where(houses["Rooms"]<20,0,1)
print(houses)


     Price  Rooms  Square_Feet  Outlier
0   534433      2         1500        0
1   392333      3         2500        0
2   293222      2         1500        0
3  4322032    116        48000        1


## **Impute Missing values**

In [ ]:
#Ex:1 Creating DataFrame
import numpy as np
import pandas as pd
students=[
    [78,'M','Good'],
    [45,'F','Avg'],
    [95,'M','Excellent'],
    ['np.NaN','F','Avg'],
    [84,'M','Very Good'],
    ['np.NaN','NONE','Excellent'],
    [25,'F','bad'],
    [86,'M','Excellent']
]
cols=['marks','gender','result']
df=pd.DataFrame(students,columns=cols)
print(df)



    marks gender     result
0      78      M       Good
1      45      F        Avg
2      95      M  Excellent
3  np.NaN      F        Avg
4      84      M  Very Good
5  np.NaN   NONE  Excellent
6      25      F        bad
7      86      M  Excellent


In [ ]:
#Ex:2 Imputing missing numeric values with mean strategy
import numpy as np
from sklearn.impute import SimpleImputer
import pandas as pd
students=[
    [78,'M','Good'],
    [45,'F','Avg'],
    [95,'M','Excellent'],
    [np.nan,'F','Avg'],
    [84,'M','Very Good'],
    [np.nan,'None','Excellent'],
    [25,'F','bad'],
    [86,'M','Excellent']
]
cols=['marks','gender','result']
df=pd.DataFrame(students,columns=cols)
print(df)
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
result=df['marks'].values.reshape(-1,1)
df.marks=imputer.fit_transform(result)
print()
print(df)


   marks gender     result
0   78.0      M       Good
1   45.0      F        Avg
2   95.0      M  Excellent
3    NaN      F        Avg
4   84.0      M  Very Good
5    NaN   None  Excellent
6   25.0      F        bad
7   86.0      M  Excellent

       marks gender     result
0  78.000000      M       Good
1  45.000000      F        Avg
2  95.000000      M  Excellent
3  68.833333      F        Avg
4  84.000000      M  Very Good
5  68.833333   None  Excellent
6  25.000000      F        bad
7  86.000000      M  Excellent


In [ ]:
#Ex:3 Imputing missing numeric values with median strategy
import numpy as np
from sklearn.impute import SimpleImputer
import pandas as pd
students=[
    [78,'M','Good'],
    [45,'F','Avg'],
    [95,'M','Excellent'],
    [np.nan,'F','Avg'],
    [84,'M','Very Good'],
    [np.nan,'None','Excellent'],
    [25,'F','bad'],
    [86,'M','Excellent']
]
cols=['marks','gender','result']
df=pd.DataFrame(students,columns=cols)
print(df)
imputer=SimpleImputer(missing_values=np.nan,strategy='median')
result=df['marks'].values.reshape(-1,1)
df.marks=imputer.fit_transform(result)
print()
print(df)

   marks gender     result
0   78.0      M       Good
1   45.0      F        Avg
2   95.0      M  Excellent
3    NaN      F        Avg
4   84.0      M  Very Good
5    NaN   None  Excellent
6   25.0      F        bad
7   86.0      M  Excellent

   marks gender     result
0   78.0      M       Good
1   45.0      F        Avg
2   95.0      M  Excellent
3   81.0      F        Avg
4   84.0      M  Very Good
5   81.0   None  Excellent
6   25.0      F        bad
7   86.0      M  Excellent


In [ ]:
#Ex:4 Imputing missing numeric values with most_frequent strategy
import numpy as np
from sklearn.impute import SimpleImputer
import pandas as pd
students=[
    [78,'M','Good'],
    [45,'F','Avg'],
    [95,'M','Excellent'],
    [np.nan,'F','Avg'],
    [84,'M','Very Good'],
    [np.nan,'None','Excellent'],
    [25,'F','bad'],
    [86,'M','Excellent']
]
cols=['marks','gender','result']
df=pd.DataFrame(students,columns=cols)
print(df)
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
result=df['marks'].values.reshape(-1,1)
df.marks=imputer.fit_transform(result)
print()
print(df)


   marks gender     result
0   78.0      M       Good
1   45.0      F        Avg
2   95.0      M  Excellent
3    NaN      F        Avg
4   84.0      M  Very Good
5    NaN   None  Excellent
6   25.0      F        bad
7   86.0      M  Excellent

   marks gender     result
0   78.0      M       Good
1   45.0      F        Avg
2   95.0      M  Excellent
3   25.0      F        Avg
4   84.0      M  Very Good
5   25.0   None  Excellent
6   25.0      F        bad
7   86.0      M  Excellent


In [ ]:
#Ex:5 Imputing missing numeric values with constant strategy
import numpy as np
from sklearn.impute import SimpleImputer
import pandas as pd
students=[
    [78,'M','Good'],
    [45,'F','Avg'],
    [95,'M','Excellent'],
    [np.nan,'F','Avg'],
    [84,'M','Very Good'],
    [np.nan,'None','Excellent'],
    [25,'F','bad'],
    [86,'M','Excellent']
]
cols=['marks','gender','result']
df=pd.DataFrame(students,columns=cols)
print(df)
imputer=SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=80)
result=df['marks'].values.reshape(-1,1)
df.marks=imputer.fit_transform(result)
print()
print(df)


   marks gender     result
0   78.0      M       Good
1   45.0      F        Avg
2   95.0      M  Excellent
3    NaN      F        Avg
4   84.0      M  Very Good
5    NaN   None  Excellent
6   25.0      F        bad
7   86.0      M  Excellent

   marks gender     result
0   78.0      M       Good
1   45.0      F        Avg
2   95.0      M  Excellent
3   80.0      F        Avg
4   84.0      M  Very Good
5   80.0   None  Excellent
6   25.0      F        bad
7   86.0      M  Excellent


# **Encoding Categorical Data**

# **1.Ordinal encoding**

In [ ]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
data=asarray([['blue'],['green'],['red']])
encoder=OrdinalEncoder()
result=encoder.fit_transform(data)
print(data)
print(result)

[['blue']
 ['green']
 ['red']]
[[0.]
 [1.]
 [2.]]


# **2. One hot encoding**

In [11]:
#Ex:1
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=[['apple'],['orange'],['apple'],['orange'],['apple']]
data=asarray(a)
encoder=OneHotEncoder(sparse_output=False)
onehot=encoder.fit_transform(data)
print(data)
print()
print(onehot)




[['apple']
 ['orange']
 ['apple']
 ['orange']
 ['apple']]

[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [12]:
#Ex:2
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=[['Apple'],['Orange'],['Mango']]
data=asarray(a)
encoder=OneHotEncoder(sparse_output=False)
onehot=encoder.fit_transform(data)
print(data)
print()
print(onehot)

[['Apple']
 ['Orange']
 ['Mango']]

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


# **Dummy variable encoding**

In [13]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=[['Apple'],['Orange'],['Mango']]
data=asarray(a)
encoder=OneHotEncoder(drop='first',sparse_output=False)
onehot=encoder.fit_transform(data)
print(data)
print()
print(onehot)

[['Apple']
 ['Orange']
 ['Mango']]

[[0. 0.]
 [0. 1.]
 [1. 0.]]


# **Imputing Missing Class Values**

In [21]:
#Ex:Imputing categorical values with most frequent strategy
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
students=[
    [85, 'M', 'verygood'],
    [95, 'F', 'excellent'],
    [75, np.nan, 'good'],
    [np.nan, 'M', 'average'],
    [70, 'M', 'good'],
    [np.nan, np.nan, 'verygood'],
    [92, 'F', 'verygood'],
    [98, 'M', 'excellent']
]
cols=['marks','gender','result']
df=pd.DataFrame(students,columns=cols)
print(df)
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
result=df['gender'].values.reshape(-1,1)
df.gender=imputer.fit_transform(result).ravel()
print()
print(df)



   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   75.0    NaN       good
3    NaN      M    average
4   70.0      M       good
5    NaN    NaN   verygood
6   92.0      F   verygood
7   98.0      M  excellent

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   75.0      M       good
3    NaN      M    average
4   70.0      M       good
5    NaN      M   verygood
6   92.0      F   verygood
7   98.0      M  excellent
